import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const P={"repo":"Siddharthsingh123456/ai-chat-assistant","name":"AI Chat Assistant","eyebrow":"CONVERSATIONAL INTELLIGENCE","desc":"A private AI workspace for questions, brainstorming, writing and problem solving.","title":"Think faster with a private AI workspace.","kind":"chat"};
function App(){const[page,setPage]=useState("home"),[user,setUser]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[authMode,setAuthMode]=useState("login"),[authMessage,setAuthMessage]=useState(""),[input,setInput]=useState(""),[output,setOutput]=useState(""),[loading,setLoading]=useState(false),[planMessage,setPlanMessage]=useState("");const[history,setHistory]=useState([]);
useEffect(()=>{const t=localStorage.getItem("ai_token");if(!t)return;fetch("/api/auth/me",{headers:{Authorization:"Bearer "+t}}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setUser(d.user)).catch(()=>{localStorage.removeItem("ai_token");localStorage.removeItem("ai_user")})},[]);
async function auth(){setAuthMessage("");try{const r=await fetch("/api/auth/"+authMode,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.error||"Authentication failed");localStorage.setItem("ai_token",d.token);localStorage.setItem("ai_user",d.user.email);setUser(d.user);setPage("workspace")}catch(e){setAuthMessage(e.message)}}
async function logout(){localStorage.removeItem("ai_token");localStorage.removeItem("ai_user");setUser(null);setPage("home")}
async function run(body){if(!user){setPage("login");return}setLoading(true);try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+localStorage.getItem("ai_token")},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||"AI request failed");setOutput(d.answer||d.result||JSON.stringify(d.quiz||d,null,2));}catch(e){setOutput(e.message)}finally{setLoading(false)}}
async function choosePlan(plan){if(!user){setPage("login");return}try{const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+localStorage.getItem("ai_token")},body:JSON.stringify({plan})});const d=await r.json();if(d.url)location.href=d.url;else setPlanMessage(d.message||"Payment configuration is ready for Stripe price IDs. Add billing environment variables to activate checkout.")}catch(e){setPlanMessage(e.message)}}


function Workspace({title,subtitle,user,input,setInput,output,loading,children}){return <section className="workspace"><div className="workspaceHead"><div><span className="eyebrow">PROTECTED AI WORKSPACE</span><h1>{title}</h1><p>{user?.email} · Secure session</p></div><button className="ghost" onClick={()=>setPage("home")}>← Product site</button></div><div className="workGrid"><div className="tool"><h2>{title}</h2><p>{subtitle}</p><div className="fields">{children}</div></div><div className="result"><div><span>AI OUTPUT</span><button className="ghost" onClick={()=>navigator.clipboard?.writeText(output||"")}>Copy</button></div><pre>{loading?"Thinking…":output||"Your AI result will appear here."}</pre></div></div></section>}

{page==="workspace"&&<Workspace title="Chat with AI" subtitle="Ask questions, brainstorm and continue a context-aware conversation." user={user} input={input} setInput={setInput} output={output} loading={loading} run={()=>run({prompt:input,history})} extra={<button className="ghost" onClick={()=>setHistory([])}>Clear history</button>} children={<><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask anything…"/><button className="primary wide" onClick={()=>{if(!input.trim())return;setHistory(h=>[...h,{role:"user",content:input}]);run({prompt:input,history});}}>Send to AI ↗</button></>} />}
return <div className="site"><header className="nav"><button className="logo" onClick={()=>setPage("home")}><span>✦</span>{P.name}</button><nav><button onClick={()=>setPage("home")}>Home</button><button onClick={()=>setPage("about")}>About</button><button onClick={()=>setPage("features")}>Features</button><button onClick={()=>setPage("pricing")}>Pricing</button></nav><div className="navActions">{user?<><button className="ghost" onClick={()=>setPage("workspace")}>Open AI</button><button className="ghost" onClick={logout}>Logout</button></>:<button className="primary" onClick={()=>setPage("login")}>Login</button>}</div></header>

{page==="home"&&<><section className="hero"><div className="heroCopy"><span className="eyebrow">{P.eyebrow}</span><h1>{P.title}</h1><p>{P.desc}</p><div className="heroBtns"><button className="primary big" onClick={()=>user?setPage("workspace"):setPage("login")}>Try {P.name} ↗</button><button className="ghost big" onClick={()=>setPage("features")}>Explore features</button></div><div className="trust"><span>⚡ Secure sessions</span><span>◈ MERN + MongoDB</span><span>✦ AI powered</span></div></div><div className="heroVisual"><div className="glow"/><div className="orb">✦</div><div className="floating f1">AUTH <b>SECURE</b></div><div className="floating f2">AI ENGINE <b>READY</b></div></div></section><section className="stats"><div><b>JWT</b><span>Protected sessions</span></div><div><b>MERN</b><span>MongoDB persistence</span></div><div><b>AI</b><span>Dedicated intelligence</span></div><div><b>24/7</b><span>Product access</span></div></section></>}
{page==="about"&&<section className="content"><span className="eyebrow">ABOUT</span><h1>Built as a complete AI product.</h1><p>{P.desc}</p><div className="cards"><article><b>Product layer</b><p>Premium responsive website with Home, About, Features, Pricing, authentication and a dedicated application workspace.</p></article><article><b>Application layer</b><p>React + Vite frontend, Express serverless API routes, MongoDB persistence and server-side AI credentials.</p></article><article><b>Security layer</b><p>Password hashing, signed access tokens, protected AI endpoints and client-side session cleanup.</p></article></div></section>}
{page==="features"&&<section className="content"><span className="eyebrow">FEATURES</span><h1>Everything needed around the AI workflow.</h1><div className="featureGrid">{["Real JWT authentication","Protected AI API","MongoDB user persistence","Dedicated AI workspace","Premium responsive UI","Usage-ready billing architecture","Secure server-side AI keys","Vercel-ready deployment"].map((x,i)=><article key={x}><span>0{i+1}</span><b>{x}</b><p>Production-oriented architecture designed for a real SaaS workflow.</p></article>)}</div></section>}
{page==="pricing"&&<section className="content"><span className="eyebrow">PRICING</span><h1>Plans ready for checkout.</h1><div className="pricing"><article><span>FREE</span><b>₹0</b><p>Core workspace access and starter usage.</p><button className="ghost" onClick={()=>user?setPage("workspace"):setPage("login")}>Start free</button></article><article className="featured"><span>PRO</span><b>₹499<span>/mo</span></b><p>Higher AI limits and saved productivity workflows.</p><button className="primary" onClick={()=>choosePlan("pro")}>Choose Pro</button></article><article><span>TEAM</span><b>₹1,499<span>/mo</span></b><p>Team-ready limits and collaboration architecture.</p><button className="ghost" onClick={()=>choosePlan("team")}>Choose Team</button></article></div><small className="note">{planMessage||"Stripe-ready checkout endpoint. Configure STRIPE_SECRET_KEY and price IDs in Vercel to activate payments."}</small></section>}
{page==="login"&&<section className="auth"><div className="authCard"><span className="eyebrow">{authMode==="login"?"WELCOME BACK":"CREATE ACCOUNT"}</span><h1>{authMode==="login"?"Sign in":"Create your account"}</h1><p>Secure access to your {P.name} workspace.</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)"/><button className="primary wide" onClick={auth}>{authMode==="login"?"Login ↗":"Create account ↗"}</button><button className="ghost wide" onClick={()=>setAuthMode(authMode==="login"?"register":"login")}>{authMode==="login"?"Need an account? Register":"Already registered? Login"}</button>{authMessage&&<small className="note">{authMessage}</small>}<small className="note">Sessions use signed access tokens. Passwords are hashed server-side.</small></div></section>}
{page==="workspace"&&!user&&<section className="content"><span className="eyebrow">AUTHENTICATION REQUIRED</span><h1>Your AI workspace is protected.</h1><p>Please sign in to continue.</p><button className="primary" onClick={()=>setPage("login")}>Login ↗</button></section>}
<footer><b>{P.name}</b><span>Built with MERN + AI</span><span>JWT auth · MongoDB · AI · Billing-ready</span></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);